query Shows($limit: Int) {
  shows(limit: $limit) {
    all_episodes_func {
      count
    }
    slug
    translations {
      description
       title
      cover {
        id
      }
     
    }
  }
}
